name: Pull Request CI

on:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            PLAYWRIGHT_BROWSERS_PATH: /home/runner/.cache/ms-playwright

        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2

            - name: Install Dependencies
              run: bun i

            - name: Lint
              run: bun lint

            - name: Check code style
              run: bun format:check

            - name: Install Playwright Chromium
              run: npx playwright install --with-deps chromium

            - name: Build Packages & Docs
              run: bun run build
